version: '3'
networks:
  nextcloud_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.80.0/20
          gateway: 192.168.80.1
  gitea_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.80.0/20
          gateway: 172.168.80.1
  komga_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.255.80.0/20
          gateway: 172.255.80.1
  monitor_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.0.80.0/20
          gateway: 172.0.80.1
  bitwarden_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.60.0/20
          gateway: 172.1.60.1
services:
  server:
    container_name: nginx
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    networks:
      nextcloud_network:
          ipv4_address: 192.168.80.2
      gitea_network:
          ipv4_address: 172.168.80.2
      komga_network:
          ipv4_address: 172.255.80.2
      bitwarden_network:
          ipv4_address: 172.1.60.2
      monitor_network:
        ipv4_address:  172.0.80.2
    environment:
      - CERTBOT_EMAIL=certbot@tdavis.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/Media/nginx/certs:/etc/letsencrypt:rw
      - /mnt/Media/nginx/conf.d:/etc/nginx/user_conf.d:rw
  cloud-db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    networks:
      nextcloud_network:
        ipv4_address: 192.168.80.4
    volumes:
      - /mnt/Media/nextcloud-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  repo-db:
    image: mariadb
    container_name: gitea-db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    networks:
      gitea_network:
        ipv4_address: 172.168.80.4
    volumes:
      - /mnt/Media/gitea-db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_DATABASE=gitea
      - MYSQL_USER=gitea
    restart: unless-stopped
  cloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
        ipv4_address: 192.168.80.3
    cap_add:
      - SYS_ADMIN
    depends_on:
      - server
      - cloud-db
    volumes:
      - /mnt/Media/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=cloud.tdavis.dev
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.tdavis.dev
    restart: unless-stopped
  repo-app:
    image: gitea/gitea:latest
    container_name: gitea-app
    networks:
      gitea_network:
        ipv4_address: 172.168.80.3
    depends_on:
      - nginx
      - repo-db
    volumes:
      - /mnt/Media/gitea:/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1002
      - USER_GID=100
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=172.168.80.4:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
  managa-app:
    image: gotson/komga:latest
    container_name: komga-app
    networks:
      komga_network:
        ipv4_address: 172.255.80.3
    depends_on:
      - nginx
    volumes:
      - /mnt/Media/komga:/config
      - /mnt/Media/content:/content:ro
      - /etc/localtime:/etc/localtime:ro
  monitor_app:
    image: nicolargo/glances:latest
    container_name: monitor-app
    pid: host
    networks:
      monitor_network:
        ipv4_address: 172.0.80.3
    depends_on:
      - nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - GLANCES_OPT=-w
  bitwarden_app:
    image: vaultwarden/server:latest
    container_name: bitwarden-app
    networks:
      bitwarden_network:
        ipv4_address: 172.1.60.3
    depends_on:
      - nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/Media/bitwarden:/data
    environment:
      WEBSOCKET_ENABLED: 'true'
      SIGNUPS_ALLOWED: false
      SIGNUPS_DOMAIN_WHITELIST: 'tdavis.dev'
      ADMIN_TOKEN: 'UoR5vX#WTZoV8xz^sCtHoVMvw%qtASf64Pwi8JfDU5'
